<?php
// Роли
const ROLE_ADMIN = 1;

const ROLES = array(ROLE_ADMIN);
const ROLE_NAMES = array(ROLE_ADMIN => 'admin');
const ROLE_LOCAL_NAMES = array(ROLE_ADMIN => 'Администратор');

// Месяца
const MONTH_JANUARY = 1;
const MONTH_FEBRUARY = 2;
const MONTH_MARCH = 3;
const MONTH_APRIL = 4;
const MONTH_MAY = 5;
const MONTH_JUNE = 6;
const MONTH_JULY = 7;
const MONTH_AUGUST = 8;
const MONTH_SEPTEMBER = 9;
const MONTH_OCTOBER = 10;
const MONTH_NOVEMBER = 11;
const MONTH_DECEMBER = 12;

const MONTHS = array(MONTH_JANUARY, MONTH_FEBRUARY, MONTH_MARCH, MONTH_APRIL, MONTH_MAY, MONTH_JUNE, MONTH_JULY, MONTH_AUGUST, MONTH_SEPTEMBER, MONTH_OCTOBER, MONTH_NOVEMBER, MONTH_DECEMBER);
const MONTH_NAMES = array(MONTH_JANUARY => "январь", MONTH_FEBRUARY => "февраль", MONTH_MARCH => "март", MONTH_APRIL => "апрель", MONTH_MAY => "май", MONTH_JUNE => "июнь", MONTH_JULY => "июль", MONTH_AUGUST => "август", MONTH_SEPTEMBER => "сентябрь", MONTH_OCTOBER => "октябрь", MONTH_NOVEMBER => "ноябрь", MONTH_DECEMBER => "декабрь");

// Типы событий
const EVENT_TYPE_ANNOUNCEMENT = 1;
const EVENT_TYPE_THEATER = 2;
const EVENT_TYPE_USTAV = 3;

const EVENT_TYPES = array(EVENT_TYPE_ANNOUNCEMENT, EVENT_TYPE_THEATER);

// Типы новостей
const NEWS_TYPE_NEWS = 1;
const NEWS_TYPE_MEDIACENTER = 2;
const NEWS_TYPE_USTAV = 3;
const NEWS_TYPE_ARTICLES = 4;

const NEWS_TYPES = array(NEWS_TYPE_NEWS, NEWS_TYPE_MEDIACENTER, NEWS_TYPE_USTAV, NEWS_TYPE_ARTICLES);

// Храмы
const TEMPLE_FADDEY = 1;
const TEMPLE_MINA = 2;
const TEMPLE_MAIN = TEMPLE_FADDEY;

const TEMPLE_NAMES = array(TEMPLE_FADDEY => "Храм сщмч. Фаддея", TEMPLE_MINA => "Храм мчч. Мины, Викентия и Виктора");
const TEMPLE_COLORS = array(TEMPLE_FADDEY => "Black", TEMPLE_MINA => "Blue");

// Священные саны
const HOLY_ORDER_MONK = 1;
const HOLY_ORDER_NUN = 2;
const HOLY_ORDER_ABBESS = 3;
const HOLY_ORDER_DEACON = 4;
const HOLY_ORDER_HIERODEACON = 5;
const HOLY_ORDER_PROTODEACON = 6;
const HOLY_ORDER_ARCHDEACON = 7;
const HOLY_ORDER_PRIEST = 8;
const HOLY_ORDER_HIEROMONK = 9;
const HOLY_ORDER_ARCHPRIEST = 10;
const HOLY_ORDER_ABBOT = 11;
const HOLY_ORDER_MITRED_ARCHPRIEST = 12;
const HOLY_ORDER_ARCHIMANDRIT = 13;
const HOLY_ORDER_BISHOP = 14;
const HOLY_ORDER_ARCHBISHOP = 15;
const HOLY_ORDER_METROPOLITAN = 16;
const HOLY_ORDER_PATRIARCH = 17;
const HOLY_ORDER_APOSTLE = 18;
const HOLY_ORDER_EQUAL_APOSTLE = 19;
const HOLY_ORDER_REVEREND = 20;
const HOLY_ORDER_PROPHET = 21;
const HOLY_ORDER_UNMERCENARY = 22;
const HOLY_ORDER_FAITHFUL = 23;
const HOLY_ORDER_MARTYR = 24;
const HOLY_ORDER_SAINT_MARTYR = 25;
const HOLY_ORDER_WHACKY = 26;
const HOLY_ORDER_BLISSFUL = 27;
const HOLY_ORDER_RIGHTEOUS = 28;

const HOLY_ORDERS = array(HOLY_ORDER_MONK, HOLY_ORDER_NUN, HOLY_ORDER_ABBESS, HOLY_ORDER_DEACON, HOLY_ORDER_HIERODEACON, HOLY_ORDER_PROTODEACON, HOLY_ORDER_ARCHDEACON, HOLY_ORDER_PRIEST, HOLY_ORDER_HIEROMONK, HOLY_ORDER_ARCHPRIEST, HOLY_ORDER_ABBOT, HOLY_ORDER_MITRED_ARCHPRIEST, HOLY_ORDER_ARCHIMANDRIT, HOLY_ORDER_BISHOP, HOLY_ORDER_ARCHBISHOP, HOLY_ORDER_METROPOLITAN, HOLY_ORDER_PATRIARCH, HOLY_ORDER_APOSTLE, HOLY_ORDER_EQUAL_APOSTLE, HOLY_ORDER_REVEREND, HOLY_ORDER_PROPHET, HOLY_ORDER_UNMERCENARY, HOLY_ORDER_FAITHFUL, HOLY_ORDER_MARTYR, HOLY_ORDER_SAINT_MARTYR, HOLY_ORDER_WHACKY, HOLY_ORDER_BLISSFUL, HOLY_ORDER_RIGHTEOUS);
const HOLY_ORDER_NAMES = array(HOLY_ORDER_MONK => "монах", HOLY_ORDER_NUN => "монахиня", HOLY_ORDER_ABBESS => "игуменья", HOLY_ORDER_DEACON => "диакон", HOLY_ORDER_HIERODEACON => "иеродиакон", HOLY_ORDER_PROTODEACON => "протодиакон", HOLY_ORDER_ARCHDEACON => "архидиакон", HOLY_ORDER_PRIEST => "священник", HOLY_ORDER_HIEROMONK => "иеромонах", HOLY_ORDER_ARCHPRIEST => "протоиерей", HOLY_ORDER_ABBOT => "игумен", HOLY_ORDER_MITRED_ARCHPRIEST => "митрофорный протоиерей", HOLY_ORDER_ARCHIMANDRIT => "архимандрит", HOLY_ORDER_BISHOP => "епископ", HOLY_ORDER_ARCHBISHOP => "архиепископ", HOLY_ORDER_METROPOLITAN => "митрополит", HOLY_ORDER_PATRIARCH => "патриарх", HOLY_ORDER_APOSTLE => "апостол", HOLY_ORDER_EQUAL_APOSTLE => "равноапостольный", HOLY_ORDER_REVEREND => "преподобный", HOLY_ORDER_PROPHET => "пророк", HOLY_ORDER_UNMERCENARY => "бессребренник", HOLY_ORDER_FAITHFUL => "благоверный", HOLY_ORDER_MARTYR => "мученик", HOLY_ORDER_SAINT_MARTYR => "священномученик", HOLY_ORDER_WHACKY => "юродивый", HOLY_ORDER_BLISSFUL => "блаженный", HOLY_ORDER_RIGHTEOUS => "праведный");

// Круги богослужения
const CYCLE_DAYLY = 1;
const CYCLE_WEEKLY = 2;
const CYCLE_YEARLY = 3;
const CYCLE_EASTER = 4;

const CYCLES = array(CYCLE_DAYLY, CYCLE_WEEKLY, CYCLE_YEARLY, CYCLE_EASTER);
const CYCLE_NAMES = array(CYCLE_DAYLY => "суточный", CYCLE_WEEKLY => "седмичный", CYCLE_YEARLY => "годовой", CYCLE_EASTER => "пасхальный цикл");

// Другое
const ISINVALID = ' is-invalid';
?>